const xlsx = require('xlsx');
const fs = require('fs');

const data = [
  {
    question: "Which of the following is the oldest discovered site of the Indus Valley Civilization?",
    questionHi: "सिंधु घाटी सभ्यता का सबसे पुराना खोजा गया स्थल निम्नलिखित में से कौन सा है?",
    optionA: "Harappa",
    optionAHi: "हड़प्पा",
    optionB: "Mohenjo-Daro",
    optionBHi: "मोहनजोदड़ो",
    optionC: "Lothal",
    optionCHi: "लोथल",
    optionD: "Kalibangan",
    optionDHi: "कालीबंगा",
    correctOption: "A",
    explanation: "Harappa was discovered in 1921 by Daya Ram Sahni, making it the first site to be excavated.",
    explanationHi: "हड़प्पा की खोज 1921 में दया राम साहनी ने की थी, जिससे यह उत्खनन किया जाने वाला पहला स्थल बन गया।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Medium"
  },
  {
    question: "The Great Bath of the Indus Valley Civilization was discovered in which city?",
    questionHi: "सिंधु घाटी सभ्यता का विशाल स्नानागार किस शहर में खोजा गया था?",
    optionA: "Harappa",
    optionAHi: "हड़प्पा",
    optionB: "Lothal",
    optionBHi: "लोथल",
    optionC: "Mohenjo-Daro",
    optionCHi: "मोहनजोदड़ो",
    optionD: "Ropar",
    optionDHi: "रोपड़",
    correctOption: "C",
    explanation: "The Great Bath, a large public bathing area, was found in Mohenjo-Daro.",
    explanationHi: "विशाल स्नानागार, जो एक बड़ा सार्वजनिक स्नान क्षेत्र है, मोहनजोदड़ो में पाया गया था।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Easy"
  },
  {
    question: "Which animal was NOT known to the people of the Indus Valley Civilization?",
    questionHi: "सिंधु घाटी सभ्यता के लोगों को किस जानवर का ज्ञान नहीं था?",
    optionA: "Bull",
    optionAHi: "बैल",
    optionB: "Horse",
    optionBHi: "घोड़ा",
    optionC: "Elephant",
    optionCHi: "हाथी",
    optionD: "Sheep",
    optionDHi: "भेड़",
    correctOption: "B",
    explanation: "The horse was generally unknown to the Indus Valley people; no concrete evidence of its widespread use has been found.",
    explanationHi: "सिंधु घाटी के लोगों को आमतौर पर घोड़े का ज्ञान नहीं था; इसके व्यापक उपयोग का कोई ठोस प्रमाण नहीं मिला है।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Medium"
  },
  {
    question: "The script of the Indus Valley Civilization was?",
    questionHi: "सिंधु घाटी सभ्यता की लिपि क्या थी?",
    optionA: "Brahmi",
    optionAHi: "ब्राह्मी",
    optionB: "Kharosthi",
    optionBHi: "खरोष्ठी",
    optionC: "Boustrophedon",
    optionCHi: "बौस्ट्रोफेडन",
    optionD: "Undeciphered",
    optionDHi: "अपठित",
    correctOption: "D",
    explanation: "The Indus script remains largely undeciphered to this day.",
    explanationHi: "सिंधु लिपि आज भी मुख्य रूप से अपठित है।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Medium"
  },
  {
    question: "Lothal, an ancient site of the Indus Valley Civilization, was famous for its?",
    questionHi: "लोथल, सिंधु घाटी सभ्यता का एक प्राचीन स्थल, किस लिए प्रसिद्ध था?",
    optionA: "Great Bath",
    optionAHi: "विशाल स्नानागार",
    optionB: "Dockyard",
    optionBHi: "गोदीवाड़ा",
    optionC: "Granary",
    optionCHi: "अन्नागार",
    optionD: "Citadel",
    optionDHi: "गढ़",
    correctOption: "B",
    explanation: "Lothal is famous for its ancient dockyard, which connected the city to an ancient course of the Sabarmati river.",
    explanationHi: "लोथल अपने प्राचीन गोदीवाड़ा के लिए प्रसिद्ध है, जो शहर को साबरमती नदी के एक प्राचीन मार्ग से जोड़ता था।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Easy"
  },
  {
    question: "The main occupation of the people of the Indus Valley Civilization was?",
    questionHi: "सिंधु घाटी सभ्यता के लोगों का मुख्य व्यवसाय क्या था?",
    optionA: "Agriculture",
    optionAHi: "कृषि",
    optionB: "Cattle rearing",
    optionBHi: "पशुपालन",
    optionC: "Hunting",
    optionCHi: "शिकार",
    optionD: "Trade",
    optionDHi: "व्यापार",
    correctOption: "A",
    explanation: "Agriculture was the main occupation, supported by the fertile floodplains of the Indus river.",
    explanationHi: "सिंधु नदी के उपजाऊ बाढ़ के मैदानों द्वारा समर्थित, कृषि मुख्य व्यवसाय था।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Medium"
  },
  {
    question: "Which metal was primarily used for making tools and weapons in the Indus Valley Civilization?",
    questionHi: "सिंधु घाटी सभ्यता में औजार और हथियार बनाने के लिए मुख्य रूप से किस धातु का उपयोग किया जाता था?",
    optionA: "Iron",
    optionAHi: "लोहा",
    optionB: "Copper",
    optionBHi: "तांबा",
    optionC: "Gold",
    optionCHi: "सोना",
    optionD: "Silver",
    optionDHi: "चांदी",
    correctOption: "B",
    explanation: "Copper and bronze were widely used; they were part of the Chalcolithic age. Iron was unknown to them.",
    explanationHi: "तांबे और कांस्य का व्यापक रूप से उपयोग किया जाता था; वे ताम्रपाषाण युग का हिस्सा थे। लोहा उन्हें ज्ञात नहीं था।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Medium"
  },
  {
    question: "The Indus Valley people worshiped primarily which deity?",
    questionHi: "सिंधु घाटी के लोग मुख्य रूप से किस देवता की पूजा करते थे?",
    optionA: "Indra",
    optionAHi: "इंद्र",
    optionB: "Pashupati Shiva",
    optionBHi: "पशुपति शिव",
    optionC: "Vishnu",
    optionCHi: "विष्णु",
    optionD: "Varuna",
    optionDHi: "वरुण",
    correctOption: "B",
    explanation: "Seals discovered at the sites suggest they worshiped a prototype of Lord Shiva, often referred to as Pashupati.",
    explanationHi: "स्थलों पर खोजे गए मुहरों से पता चलता है कि वे भगवान शिव के एक प्रारंभिक रूप की पूजा करते थे, जिसे अक्सर पशुपति कहा जाता है।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Easy"
  },
  {
    question: "What was the primary material used for the construction of houses in the Indus Valley Civilization?",
    questionHi: "सिंधु घाटी सभ्यता में घरों के निर्माण के लिए मुख्य रूप से किस सामग्री का उपयोग किया जाता था?",
    optionA: "Wood",
    optionAHi: "लकड़ी",
    optionB: "Stone",
    optionBHi: "पत्थर",
    optionC: "Baked bricks",
    optionCHi: "पक्की ईंटें",
    optionD: "Mud",
    optionDHi: "मिट्टी",
    correctOption: "C",
    explanation: "The Indus Valley Civilization is noted for its advanced urban planning and extensive use of baked bricks for construction.",
    explanationHi: "सिंधु घाटी सभ्यता अपनी उन्नत शहरी योजना और निर्माण के लिए पक्की ईंटों के व्यापक उपयोग के लिए जानी जाती है।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Easy"
  },
  {
    question: "Which of the following sites of the Indus Valley Civilization is located in present-day Gujarat?",
    questionHi: "सिंधु घाटी सभ्यता का निम्नलिखित में से कौन सा स्थल वर्तमान गुजरात में स्थित है?",
    optionA: "Kalibangan",
    optionAHi: "कालीबंगा",
    optionB: "Rakhigarhi",
    optionBHi: "राखीगढ़ी",
    optionC: "Banawali",
    optionCHi: "बनावली",
    optionD: "Dholavira",
    optionDHi: "धोलावीरा",
    correctOption: "D",
    explanation: "Dholavira is an archaeological site at Khadirbet in Bhachau Taluka of Kutch District, in the state of Gujarat.",
    explanationHi: "धोलावीरा गुजरात राज्य के कच्छ जिले के भचाऊ तालुका में खादिरबेट में एक पुरातात्विक स्थल है।",
    marks: 1,
    negativeMarks: 0.25,
    perQuestionTime: 60,
    subject: "history",
    chapter: "Ancient Indian History (प्राचीन भारत)",
    topic: "Indus Valley Civilization",
    difficulty: "Medium"
  }
];

// Add missing columns as empty to match template exactly
const templateCols = [
  'question', 'questionHi',
  'optionA', 'optionB', 'optionC', 'optionD',
  'optionAHi', 'optionBHi', 'optionCHi', 'optionDHi',
  'correctOption', 'explanation', 'explanationHi', 'marks',
  'negativeMarks', 'perQuestionTime', 'subject', 'chapter',
  'topic', 'difficulty', 'questionImage', 'questionImageHi',
  'optionAImage', 'optionAImageHi', 'optionBImage', 'optionBImageHi',
  'optionCImage', 'optionCImageHi', 'optionDImage', 'optionDImageHi',
  'explanationImage', 'explanationImageHi'
];

const processedData = data.map(item => {
  const row = {};
  templateCols.forEach(col => {
    row[col] = item[col] !== undefined ? item[col] : "";
  });
  return row;
});

const wb = xlsx.utils.book_new();
const ws = xlsx.utils.json_to_sheet(processedData, { header: templateCols });

xlsx.utils.book_append_sheet(wb, ws, "Sheet1");
xlsx.writeFile(wb, "history_indus_valley_bulk_questions.xlsx");

console.log("Excel file generated successfully.");
