const Joi = require('joi')

const createDailyQuizSchema = Joi.object({
    title: Joi.string().trim().required(),
    description: Joi.string().optional().allow(null, ''),
    thumbnail: Joi.string().optional().allow(null, ''),
    duration: Joi.number().integer().min(1).required(),
    totalQuestions: Joi.number().integer().min(1).required(),
    totalMarks: Joi.number().min(0).required(),
    marksPerQuestion: Joi.number().min(0).required(),
    negativeMarks: Joi.number().min(0).required(),
    passingMarks: Joi.number().min(0).required(),
    instructions: Joi.string().optional().allow(null, ''),
    instructionsNew: Joi.string().trim().optional().allow(null, ''),
    startDateTime: Joi.date().required(),
    endDateTime: Joi.date().greater(Joi.ref('startDateTime')).required(),
    scheduleAt: Joi.date().optional().allow(null, ''),
    isPaid: Joi.boolean().optional().default(false),
    status: Joi.string().valid('active', 'inactive').optional().default('active'),
    language: Joi.string().valid('en', 'hi', 'both').optional().default('en'),
    exam: Joi.string().regex(/^[0-9a-fA-F]{24}$/).optional(),
    examId: Joi.string().regex(/^[0-9a-fA-F]{24}$/).optional(),
    subExams: Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional().default([]),
    subExamIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string()).optional(),
    subjectIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string().regex(/^[0-9a-fA-F]{24}$/)).required(),
    chapterIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional().default([]),
    topicIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional().default([]),
}).or('exam', 'examId')

const updateDailyQuizSchema = Joi.object({
    title: Joi.string().trim(),
    description: Joi.string().optional().allow(null, ''),
    thumbnail: Joi.string().optional().allow(null, ''),
    duration: Joi.number().integer().min(1),
    totalQuestions: Joi.number().integer().min(1),
    totalMarks: Joi.number().min(0),
    marksPerQuestion: Joi.number().min(0),
    negativeMarks: Joi.number().min(0),
    passingMarks: Joi.number().min(0),
    instructions: Joi.string().optional().allow(null, ''),
    instructionsNew: Joi.string().trim().optional().allow(null, ''),
    startDateTime: Joi.date(),
    endDateTime: Joi.date(),
    scheduleAt: Joi.date().optional().allow(null, ''),
    isPaid: Joi.boolean().optional(),
    status: Joi.string().valid('active', 'inactive').optional(),
    language: Joi.string().valid('en', 'hi', 'both').optional(),
    exam: Joi.string().regex(/^[0-9a-fA-F]{24}$/).optional(),
    examId: Joi.string().regex(/^[0-9a-fA-F]{24}$/).optional(),
    subExams: Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional(),
    subExamIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string()).optional(),
    subjectIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional(),
    chapterIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional(),
    topicIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional(),
}).min(1)

const bulkCreateDailyQuizSchema = Joi.array().items(
    Joi.object({
        title: Joi.string().trim().required(),
        description: Joi.string().optional().allow(null, ''),
        thumbnail: Joi.string().optional().allow(null, '').default(''),
        duration: Joi.number().integer().min(1).required(),
        totalQuestions: Joi.number().integer().min(1).required(),
        totalMarks: Joi.number().min(0).required(),
        marksPerQuestion: Joi.number().min(0).required(),
        negativeMarks: Joi.number().min(0).required(),
        passingMarks: Joi.number().min(0).required(),
        instructions: Joi.string().optional().allow(null, ''),
        instructionsNew: Joi.string().trim().optional().allow(null, ''),
        startDateTime: Joi.date().required(),
        endDateTime: Joi.date().required(),
        scheduleAt: Joi.date().optional().allow(null, ''),
        isPaid: Joi.boolean().optional().default(false),
        status: Joi.string().valid('active', 'inactive').optional().default('active'),
        language: Joi.string().valid('en', 'hi', 'both').optional().default('en'),
        exam: Joi.string().regex(/^[0-9a-fA-F]{24}$/).required(),
        subExams: Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional().default([]),
        subjectIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional().default([]),
        chapterIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional().default([]),
        topicIds: Joi.alternatives().try(Joi.array().items(Joi.string().regex(/^[0-9a-fA-F]{24}$/)), Joi.string().regex(/^[0-9a-fA-F]{24}$/)).optional().default([]),
    })
)

module.exports = { createDailyQuizSchema, updateDailyQuizSchema, bulkCreateDailyQuizSchema }
