const Joi = require('joi')

const createCourseTestSchema = Joi.object({
  course: Joi.string().hex().length(24).required(),
  courseId: Joi.string().hex().length(24).optional(),
  subjects: Joi.array().items(Joi.string().hex().length(24)).optional(),
  topics: Joi.array().items(Joi.string().hex().length(24)).optional(),
  chapters: Joi.array().items(Joi.string().hex().length(24)).optional(),
  title: Joi.string().trim().required(),
  slug: Joi.string().trim(),
  description: Joi.string().trim().optional().allow('', null),
  instruction: Joi.string().trim().optional().allow('', null),
  image: Joi.string().trim().optional().allow('', null),
  duration: Joi.number().min(1).required(),
  sortOrder: Joi.number().integer().min(0).default(0),
  totalQuestions: Joi.number().min(0).default(0),
  totalMarks: Joi.number().min(0).default(0),
  passingMarks: Joi.number().min(0).default(0),
  marksPerQuestion: Joi.number().min(1).default(1),
  negativeMarks: Joi.number().min(0).default(0),
  maxAttempts: Joi.number().min(1).default(1),
  difficulty: Joi.string().valid('easy', 'medium', 'hard').default('medium'),
  testType: Joi.string().valid('practice', 'mock', 'exam').default('practice'),
  startDate: Joi.date().optional(),
  endDate: Joi.date().optional(),
  language: Joi.string().valid('hi', 'en', 'both').default('hi'),
  status: Joi.string().valid('draft', 'active', 'inactive').default('draft'),
})

const updateCourseTestSchema = Joi.object({
  course: Joi.string().hex().length(24).optional(),
  courseId: Joi.string().hex().length(24).optional(),
  subjects: Joi.array().items(Joi.string().hex().length(24)).optional(),
  topics: Joi.array().items(Joi.string().hex().length(24)).optional(),
  chapters: Joi.array().items(Joi.string().hex().length(24)).optional(),
  title: Joi.string().trim(),
  slug: Joi.string().trim(),
  description: Joi.string().trim().optional().allow('', null),
  instruction: Joi.string().trim().optional().allow('', null),
  image: Joi.string().trim().optional().allow('', null),
  duration: Joi.number().min(1),
  sortOrder: Joi.number().integer().min(0),
  totalQuestions: Joi.number().min(0),
  totalMarks: Joi.number().min(0),
  passingMarks: Joi.number().min(0),
  marksPerQuestion: Joi.number().min(1),
  negativeMarks: Joi.number().min(0),
  maxAttempts: Joi.number().min(1),
  difficulty: Joi.string().valid('easy', 'medium', 'hard'),
  testType: Joi.string().valid('practice', 'mock', 'exam'),
  startDate: Joi.date().optional(),
  endDate: Joi.date().optional(),
  language: Joi.string().valid('hi', 'en', 'both'),
  status: Joi.string().valid('draft', 'active', 'inactive'),
}).min(1)

const listCourseTestQuerySchema = Joi.object({
  status: Joi.string().valid('draft', 'active', 'inactive'),
  course: Joi.string().hex().length(24),
  subject: Joi.string().hex().length(24),
  topic: Joi.string().hex().length(24),
  chapter: Joi.string().hex().length(24),
  search: Joi.string().trim().max(200),
  sortBy: Joi.string().valid('createdAt', 'sortOrder').default('sortOrder'),
  order: Joi.string().valid('asc', 'desc').default('asc'),
  page: Joi.number().integer().min(1).default(1),
  limit: Joi.number().integer().min(1).max(100).default(20),
})

module.exports = { createCourseTestSchema, updateCourseTestSchema, listCourseTestQuerySchema }
