const router = require('express').Router()
const { requirePermission } = require('../middlewares/permission.middleware')

router.use('/cms', require('./cms/admin-cms.routes'))
router.use('/app-version', require('./app-version/admin-app-version.routes'))

router.use('/courses', requirePermission('courses'), require('./courses/admin-course.routes'))
router.use('/tests', requirePermission('tests'), require('./tests/admin-test.routes'))
router.use('/test-series', requirePermission('tests'), require('./test-series/admin-test-series.routes'))
router.use('/test-series-tests', requirePermission('tests'), require('./test-series-tests/admin-test-series-test.routes'))
router.use('/previous-year-papers', requirePermission('tests'), require('./previous-year-papers/admin-previous-year-paper.routes'))
router.use('/previous-year-paper-tests', requirePermission('tests'), require('./previous-year-paper-tests/admin-previous-year-paper-test.routes'))
router.use('/today-quizzes', requirePermission('tests'), require('./today-quizzes/admin-today-quiz.routes'))
router.use('/live-tests', requirePermission('tests'), require('./live-tests/admin-live-test.routes'))
router.use('/boosters', requirePermission('boosters'), require('./boosters/admin-booster.routes'))
router.use('/users', requirePermission('users'), require('./users/admin-user.routes'))
router.use('/blog', requirePermission('blog'), require('./blog/admin-blog.routes'))
router.use('/analytics', requirePermission('analytics'), require('./analytics/admin-analytics.routes'))
router.use('/notifications', requirePermission('notifications'), require('./notifications/admin-notification.routes'))
router.use('/admins', requirePermission('admins'), require('./admins/admin-admins.routes'))
router.use('/permissions', requirePermission('admins'), require('./permissions/admin-permission.routes'))
router.use('/roles', requirePermission('admins'), require('./roles/admin-role.routes'))
router.use('/members', requirePermission('admins'), require('./members/admin-member.routes'))
router.use('/exams', requirePermission('exams'), require('./exams/admin-exam.routes'))
router.use('/subexams', requirePermission('subexams'), require('./subexams/admin-subexam.routes'))
router.use('/subjects', requirePermission('subjects'), require('./subjects/admin-subject.routes'))
router.use('/banners', requirePermission('banners'), require('./banners/admin-banner.routes'))
router.use('/topics', requirePermission('topics'), require('./topics/admin-topic.routes'))
router.use('/grammars', requirePermission('grammars'), require('./grammars/admin-grammar.routes'))
router.use('/faqs', requirePermission('faqs'), require('./faqs/admin-faq.routes'))
router.use('/pdfs', requirePermission('pdfs'), require('./pdfs/admin-pdf.routes'))
router.use('/contents', requirePermission('pdfs'), require('./contents/admin-content.routes'))
router.use('/course-tests', requirePermission('tests'), require('./course-tests/admin-course-test.routes'))
router.use('/questions', requirePermission('tests'), require('./questions/admin-question.routes'))
router.use('/books', requirePermission('books'), require('./books/admin-book.routes'))
router.use('/shorts', requirePermission('shorts'), require('./shorts/admin-short.routes'))
router.use('/qualifications', requirePermission('qualifications'), require('./qualifications/admin-qualification.routes'))
router.use('/vocabulary', requirePermission('vocabulary'), require('./vocabulary/admin-vocabulary.routes'))
router.use('/editorials', requirePermission('editorial'), require('./editorials/admin-editorial.routes'))
router.use('/editorial-tests', requirePermission('editorial'), require('./editorial-tests/admin-editorial-test.routes'))
router.use('/editorial-questions', requirePermission('editorial'), require('./editorial-questions/admin-editorial-question.routes'))


module.exports = router